# Generated by Django 6.1 on 2026-08-30 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas/'),
        ),
    ]
